name: Update Countries Data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node 16 kur
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bağımlılıkları yükle
        run: npm install axios cheerio

     - name: Scraper'ı çalıştır
  env:
    NODE_OPTIONS: "--no-experimental-fetch --no-warnings"
  run: node --no-experimental-fetch --no-warnings scripts/scraper.js
