name: Update Countries Data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Scraper bağımlılıkları
        run: npm install cheerio axios

      - name: Scraper'ı çalıştır
        env:
          NODE_NO_UNDICI: 1
        run: node scripts/scraper.js
