name: Update Countries Data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node 16 kur
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bağımlılıkları yükle
        run: npm install axios cheerio

      - name: Scraper'ı çalıştır
        env:
          NODE_NO_FETCH: "1"
          NODE_OPTIONS: "--no-experimental-fetch"
          DISABLE_UNDICI: "1"
          NO_UNDICI: "1"
        run: node scripts/scraper.js
