name: Update Countries Data

on:
  schedule:
    # Salı, Çarşamba, Perşembe günleri
    # TR Saati 20:00 - 00:00 → UTC 17:00 - 21:00
    - cron: "*/15 17-21 * * 2,3,4"

  # Manuel çalıştırmak için
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v3

      - name: Node kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Scraper bağımlılıkları
        run: npm install cheerio


      - name: Scraper'ı çalıştır
        run: node scripts/scraper.js

      - name: Değişiklikleri commit et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update countries data" || echo "No changes"
          git push
